Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['UTEST_MEMHEAP_TC']):
    src += ['memheap_tc.c']

if GetDepend(['UTEST_IRQ_TC']):
    src += ['irq_tc.c']

if GetDepend(['UTEST_SEMAPHORE_TC']):
    src += ['semaphore_tc.c']

if GetDepend(['UTEST_EVENT_TC']):
    src += ['event_tc.c']

if GetDepend(['UTEST_TIMER_TC']):
    src += ['timer_tc.c']

if GetDepend(['UTEST_MESSAGEQUEUE_TC']):
    src += ['messagequeue_tc.c']

if GetDepend(['UTEST_MUTEX_TC']):
    src += ['mutex_tc.c']

if GetDepend(['UTEST_MAILBOX_TC']):
    src += ['mailbox_tc.c']

if GetDepend(['UTEST_THREAD_TC']):
    src += ['thread_tc.c']
    src += ['vector_tc.c']

if GetDepend(['UTEST_MMU_TC']):
    src += ['mmu_tc.c']

group = DefineGroup('utestcases', src, depend = ['RT_USING_UTEST'], CPPPATH = CPPPATH)

Return('group')
