from building import *

# The set of source files associated with this SConscript file.
src = Glob('*.c')
cwd = GetCurrentDir()
CPPPATH = [cwd + "/include"]
group = []
if GetDepend('RT_USING_LWP'):
    group = DefineGroup('tty', src, depend = ['RT_USING_TTY'], CPPPATH = CPPPATH)
    
Return('group')
