import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.

src = Split('''
../CMSIS/Device/ST/STM32H7RSxx/Source/Templates/system_stm32h7rsxx.c
Src/stm32h7rsxx_hal.c
Src/stm32h7rsxx_hal_cec.c
Src/stm32h7rsxx_hal_cortex.c
Src/stm32h7rsxx_hal_crc.c
Src/stm32h7rsxx_hal_crc_ex.c
Src/stm32h7rsxx_hal_cryp.c
Src/stm32h7rsxx_hal_cryp_ex.c
Src/stm32h7rsxx_hal_dma.c
Src/stm32h7rsxx_hal_dma_ex.c
Src/stm32h7rsxx_hal_pwr.c
Src/stm32h7rsxx_hal_pwr_ex.c
Src/stm32h7rsxx_hal_rcc.c
Src/stm32h7rsxx_hal_rcc_ex.c
Src/stm32h7rsxx_hal_rng.c
Src/stm32h7rsxx_hal_sram.c
Src/stm32h7rsxx_hal_gpio.c
Src/stm32h7rsxx_hal_adc.c
Src/stm32h7rsxx_hal_adc_ex.c
Src/stm32h7rsxx_hal_xspi.c
Src/stm32h7rsxx_hal_flash.c
Src/stm32h7rsxx_hal_flash_ex.c
''')

if rtconfig.CROSS_TOOL == 'gcc':
    src += [cwd + '/../../libraries/CMSIS/Device/ST/STM32H7RSxx/Source/Templates/gcc/startup_stm32h7r7xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [cwd + '/../../libraries/CMSIS/Device/ST/STM32H7RSxx/Source/Templates/arm/startup_stm32h7r7xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [cwd + '/../../libraries/CMSIS/Device/ST/STM32H7RSxx/Source/Templates/iar/startup_stm32h7r7xx.s']

if GetDepend(['RT_USING_SERIAL']):
    src += ['Src/stm32h7rsxx_hal_uart.c']
    src += ['Src/stm32h7rsxx_hal_usart.c']
    src += ['Src/stm32h7rsxx_hal_uart_ex.c']

if GetDepend(['RT_USING_SDIO']):
    src += ['Src/stm32h7rsxx_ll_sdmmc.c']
    src += ['Src/stm32h7rsxx_hal_sd.c']

if GetDepend(['RT_USING_SPI']):
    src += ['Src/stm32h7rsxx_hal_spi.c']

# if GetDepend(['RT_USING_CAN']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.c']

# if GetDepend(['RT_USING_HWTIMER']) or GetDepend(['RT_USING_PWM']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.c']

# if GetDepend(['BSP_USING_ETH']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c']

#if GetDepend(['RT_USING_ADC']):
#    src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c']
#    src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c']

# if GetDepend(['RT_USING_RTC']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c']

# if GetDepend(['RT_USING_WDT']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.c']

# if GetDepend(['RT_USING_AUDIO']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.c']

# if GetDepend(['RT_USING_MTD_NOR']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.c']

# if GetDepend(['RT_USING_MTD_NAND']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.c']

# if GetDepend(['BSP_USING_PSRAM']):
#     src += ['Src/stm32h7rsxx_hal_xspi.c']

# if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c']
#     src += ['STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c']

if GetDepend(['BSP_USING_LCD']):
    src += ['Src/stm32h7rsxx_hal_ltdc.c']
    src += ['Src/stm32h7rsxx_hal_dma2d.c']
    src += ['Src/stm32h7rsxx_hal_jpeg.c']

if GetDepend(['ART_PI_TouchGFX_LIB']):
    src += ['Src/stm32h7rsxx_hal_ltdc.c']
    src += ['Src/stm32h7rsxx_hal_dma2d.c']
    src += ['Src/stm32h7rsxx_hal_jpeg.c']
    src += ['Src/stm32h7rsxx_hal_gpu2d.c']
    src += ['Src/stm32h7rsxx_hal_icache.c']
    src += ['Src/stm32h7rsxx_hal_gfxmmu.c']

path = [cwd + '/Inc',
    cwd + '/../CMSIS/Device/ST/STM32H7RSxx/Include',
    cwd + '/../CMSIS/Include']

CPPDEFINES = ['USE_HAL_DRIVER']
group = DefineGroup('STM32_HAL', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')

