import os
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Glob('*.c')
src += Glob('port/*.c')

# add cubemx drivers
src += Split('''
CubeMX_Config/Appli/Core/Src/stm32h7rsxx_hal_msp.c
''')

path = [cwd]
path += [cwd + '/port']
path += [cwd + '/CubeMX_Config/Appli/Core/Inc']

startup_path_prefix = SDK_LIB

if rtconfig.CROSS_TOOL == 'gcc':
    src += [startup_path_prefix + '/STM32H7RSxx_HAL/CMSIS/Device/ST/STM32H7RSxx/Source/Templates/gcc/startup_stm32h7r7xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [startup_path_prefix + '/STM32H7RSxx_HAL/CMSIS/Device/ST/STM32H7RSxx/Source/Templates/arm/startup_stm32h7r7xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [startup_path_prefix + '/STM32H7RSxx_HAL/CMSIS/Device/ST/STM32H7RSxx/Source/Templates/iar/startup_stm32h7r7xx.s']

CPPDEFINES = ['STM32H7S7xx']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
